### ISSUE TITLE
Build fails with current ia16elf-gcc

### ISSUE THREAD

**Issue by andrewbird** [PerditionC/fdkernel#28]
I didn't try building FreeDOS before with this compiler, so after reading docs/build.txt I did
~~~
cp config.m config.mak
make all COMPILER=gcc
~~~
But I get
~~~
ia16-elf-gcc -c -DI386 -DWITHFAT32 -I../hdr -march=i80286 -mcmodel=small -fleading-underscore -fno-common -fpack-struct -ffreestanding -fcall-used-es -mrtd -Wno-pointer-to-int-cast -Wno-pragmas -Werror -Os -fno-strict-aliasing -o main.obj main.c
In file included from main.c:30:0:
main.c: In function ‘setup_int_vectors’:
../hdr/portab.h:340:31: error: initialiser element is not constant
 #define FP_OFF(fp)            ((unsigned)(fp))
                               ^
main.c:251:14: note: in expansion of macro ‘FP_OFF’
       { 0x0, FP_OFF(int0_handler) },   /* zero divide */
              ^~~~~~
../hdr/portab.h:340:31: note: (near initialisation for ‘vectors[0].handleroff’)
 #define FP_OFF(fp)            ((unsigned)(fp))
~~~

The compiler is
~~~
gcc-ia16-elf/bionic,now 6.3.0-20181013.16-ppa181014071~bionic i386 [installed]
  GNU C and C++ compilers for ia16-elf target
~~~
from tkchia http://ppa.launchpad.net/tkchia/build-ia16/ubuntu

**Comment by andrewbird** [comment]
I'm not sure what the fork hierarchy is here for fdkernel, this repo is the only one configured to report issues, but FDOS repo seems to have included the @tkchia commit 49d1939 from his fork that seems related?

**Comment by PerditionC** [comment]
Sorry I didn't notice this was the one on my account.  I forked it to fdos since that is where I am trying to have all the core/base programs.  Please try that one.  All future work should be done with it.  I haven't decided yet what to do with this repository.

**Comment by andrewbird** [comment]
Thanks, it builds again now.

Regarding the move to FDOS, what's to be done with open issues and PRs that are here, should they be duplicated or dealt with here and no new ones are allowed to be opened?

**Comment by tkchia** [comment]
Hello @andrewbird ,

> FDOS repo seems to have included the @tkchia commit [`49d1939`](https://github.com/PerditionC/fdkernel/commit/49d1939ed7e9b95d6b06feeef8cd9bc78c1e582f) from his fork that seems related?

Yes --- I recently modified `gcc-ia16` so that it will by default interpret `void __far int0_handler (void);`, int __far blk_driver (request __far *);`, etc. as far function declarations, rather than near function declarations (please see the [related discussion](https://github.com/tkchia/gcc-ia16/issues/19#issuecomment-403287223)).

(Incidentally, you can still get the old behaviour by specifying `-mno-far-function-if-far-return-type`, in case you need to.)

As a side effect, the change caused the expression `FP_OFF (int0_handler)` under the old definition of `FP_OFF` to break, when used within a static variable initializer.

Thank you!

**Comment by PerditionC** [comment]
I will probably refile the issues and resolve the PRs in place.  Once I refile the issues I will disable on this fork to help reduce confusion and duplication of effort.  PRs can (usually) easily be handled on either fork since my intention is to keep them in sync.  I would actually like to remove this fork but I'm not certain how that would effect other forks and future merging.

**Comment by andrewbird** [comment]
I think this issue can be closed now. Thanks for all your help,
